In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_PATH = Path.cwd().parent
DATA_PATH = PROJECT_PATH / "data" / "raw"

print("Project:", PROJECT_PATH)
print("Data:", DATA_PATH)

Project: c:\Users\User\Desktop\foresight
Data: c:\Users\User\Desktop\foresight\data\raw

In [2]:
foresight_files = [
    "sales_daily.csv",
    "calendar.csv",
    "inventory_snapshots.csv",
    "sku_master.csv"
]

for filename in foresight_files:
    file_path = DATA_PATH / filename

    print("\n" + "=" * 70)
    print(filename)
    print("=" * 70)

    if file_path.exists():
        df = pd.read_csv(file_path)

        print("Rows:", len(df))
        print("Columns:", len(df.columns))
        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())

    else:
        print("❌ FILE NOT FOUND")

======================================================================
sales_daily.csv
======================================================================
Rows: 36550
Columns: 6
Shape: (36550, 6)
Columns: ['Date', 'SKU', 'Units_Sold', 'Revenue', 'Price', 'Promotion']

======================================================================
calendar.csv
======================================================================
Rows: 731
Columns: 11
Shape: (731, 11)
Columns: ['date', 'year', 'month', 'quarter', 'week', 'day_of_week', 'is_weekend', 'season', 'holiday', 'is_holiday', 'promotion_event']

======================================================================
inventory_snapshots.csv
======================================================================
Rows: 4800
Columns: 8
Shape: (4800, 8)
Columns: ['Snapshot_Date', 'SKU', 'Current_Stock', 'On_Order', 'Lead_Time_Days', 'Safety_Stock', 'Reorder_Point', 'Inventory_Value']

======================================================================
sku_master.csv
======================================================================
Rows: 5000
Columns: 7
Shape: (5000, 7)
Columns: ['sku_id', 'sku_name', 'category', 'subcategory', 'unit_price', 'cost_price', 'brand']

In [3]:
from pathlib import Path
import pandas as pd
import numpy as np
PROJECT_PATH = Path.cwd().parent
DATA_PATH = PROJECT_PATH / "data" / "raw"
print("Project path:", PROJECT_PATH)
print("Data path:", DATA_PATH)

Project path: c:\Users\User\Desktop\foresight
Data path: c:\Users\User\Desktop\foresight\data\raw

In [4]:
# ==========================================
# 2. LOAD CORE DATASETS
# ==========================================

sales_daily = pd.read_csv(
    DATA_PATH / "sales_daily.csv"
)

calendar = pd.read_csv(
    DATA_PATH / "calendar.csv"
)

inventory = pd.read_csv(
    DATA_PATH / "inventory_snapshots.csv"
)

sku_master = pd.read_csv(
    DATA_PATH / "sku_master.csv"
)
print("Sales daily:", sales_daily.shape)
print("Calendar:", calendar.shape)
print("Inventory snapshots:", inventory.shape)
print("SKU master:", sku_master.shape)

Sales daily: (36550, 6)
Calendar: (731, 11)
Inventory snapshots: (4800, 8)
SKU master: (5000, 7)

In [5]:
datasets = {
    "sales_daily": sales_daily,
    "calendar": calendar,
    "inventory": inventory,
    "sku_master": sku_master}
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Column names:", df.columns.tolist())

======================================================================
SALES_DAILY
======================================================================
Rows: 36550
Columns: 6
Column names: ['Date', 'SKU', 'Units_Sold', 'Revenue', 'Price', 'Promotion']

======================================================================
CALENDAR
======================================================================
Rows: 731
Columns: 11
Column names: ['date', 'year', 'month', 'quarter', 'week', 'day_of_week', 'is_weekend', 'season', 'holiday', 'is_holiday', 'promotion_event']

======================================================================
INVENTORY
======================================================================
Rows: 4800
Columns: 8
Column names: ['Snapshot_Date', 'SKU', 'Current_Stock', 'On_Order', 'Lead_Time_Days', 'Safety_Stock', 'Reorder_Point', 'Inventory_Value']

======================================================================
SKU_MASTER
======================================================================
Rows: 5000
Columns: 7
Column names: ['sku_id', 'sku_name', 'category', 'subcategory', 'unit_price', 'cost_price', 'brand']

In [6]:
print("SALES DAILY")
display(sales_daily.head())

print("\nCALENDAR")
display(calendar.head())

print("\nINVENTORY SNAPSHOTS")
display(inventory.head())

print("\nSKU MASTER")
display(sku_master.head())

SALES DAILY

         Date     SKU  Units_Sold    Revenue    Price  Promotion
0  2024-01-01  SKU001           5   18320.25  3664.05          0
1  2024-01-01  SKU002          15   57085.35  3805.69          0
2  2024-01-01  SKU003           5   40391.15  8078.23          0
3  2024-01-01  SKU004           5   34307.85  6861.57          0
4  2024-01-01  SKU005          12  113918.64  9493.22          0

CALENDAR

,date,year,month,quarter,week,day_of_week,is_weekend,season,holiday,is_holiday,promotion_event
0,2024-01-01,2024,1,Q1,1,Monday,0,Winter,NaN,0,NaN
1,2024-01-02,2024,1,Q1,1,Tuesday,0,Winter,NaN,0,NaN
2,2024-01-03,2024,1,Q1,1,Wednesday,0,Winter,NaN,0,NaN
3,2024-01-04,2024,1,Q1,1,Thursday,0,Winter,NaN,0,NaN
4,2024-01-05,2024,1,Q1,1,Friday,0,Winter,NaN,0,NaN

INVENTORY SNAPSHOTS

,Snapshot_Date,SKU,Current_Stock,On_Order,Lead_Time_Days,Safety_Stock,Reorder_Point,Inventory_Value
0,2024-01-01,SKU001,16,23,11,7,18,58420.96
1,2024-01-01,SKU002,29,12,4,5,10,163983.40
2,2024-01-01,SKU003,34,23,14,6,20,209060.22
3,2024-01-01,SKU004,34,4,7,5,12,42257.92
4,2024-01-01,SKU005,23,5,5,6,11,170945.89

SKU MASTER

,sku_id,sku_name,category,subcategory,unit_price,cost_price,brand
0,SKU00001,NutriPlus Cookware Large,Home & Kitchen,Cookware,813.41,619.77,NutriPlus
1,SKU00002,CrispKing Bread Family Pack,Dairy & Bakery,Bread,70.38,49.57,CrispKing
2,SKU00003,SoftTouch Notebooks 2L,Stationery & Office,Notebooks,151.28,83.67,SoftTouch
3,SKU00004,SunriseFoods Eggs Large,Dairy & Bakery,Eggs,233.64,156.32,SunriseFoods
4,SKU00005,SunriseFoods Pest Control Pack of 6,Home Care,Pest Control,138.50,83.46,SunriseFoods

In [7]:
for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    print("\nData types:")
    print(df.dtypes)
    print("\nMissing values:")
    print(df.isna().sum())

======================================================================
SALES_DAILY
======================================================================

Data types:
Date              str
SKU               str
Units_Sold      int64
Revenue       float64
Price         float64
Promotion       int64
dtype: object

Missing values:
Date          0
SKU           0
Units_Sold    0
Revenue       0
Price         0
Promotion     0
dtype: int64

======================================================================
CALENDAR
======================================================================

Data types:
date                 str
year               int64
month              int64
quarter              str
week               int64
day_of_week          str
is_weekend         int64
season               str
holiday              str
is_holiday         int64
promotion_event      str
dtype: object

Missing values:
date                 0
year                 0
month                0
quarter              0
week                 0
day_of_week          0
is_weekend           0
season               0
holiday            723
is_holiday           0
promotion_event    656
dtype: int64

======================================================================
INVENTORY
======================================================================

Data types:
Snapshot_Date          str
SKU                    str
Current_Stock        int64
On_Order             int64
Lead_Time_Days       int64
Safety_Stock         int64
Reorder_Point        int64
Inventory_Value    float64
dtype: object

Missing values:
Snapshot_Date      0
SKU                0
Current_Stock      0
On_Order           0
Lead_Time_Days     0
Safety_Stock       0
Reorder_Point      0
Inventory_Value    0
dtype: int64

======================================================================
SKU_MASTER
======================================================================

Data types:
sku_id             str
sku_name           str
category           str
subcategory        str
unit_price     float64
cost_price     float64
brand              str
dtype: object

Missing values:
sku_id         0
sku_name       0
category       0
subcategory    0
unit_price     0
cost_price     0
brand          0
dtype: int64

In [8]:
print("DUPLICATES")
print("-" * 40)
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()}")
print("\nDATE RANGES")
print("-" * 40)
print(
    "Sales:",
    sales_daily["Date"].min(),
    "to",
    sales_daily["Date"].max())
print(
    "Calendar:",
    calendar["date"].min(),
    "to",
    calendar["date"].max())
print(
    "Inventory:",
    inventory["Snapshot_Date"].min(),
    "to",
    inventory["Snapshot_Date"].max()
)

print("\nINVALID DATES")
print("-" * 40)

print("Sales:", sales_daily["Date"].isna().sum())
print("Calendar:", calendar["date"].isna().sum())
print("Inventory:", inventory["Snapshot_Date"].isna().sum())

DUPLICATES
----------------------------------------
sales_daily: 0
calendar: 0
inventory: 0
sku_master: 0

DATE RANGES
----------------------------------------
Sales: 2024-01-01 to 2025-12-31
Calendar: 2024-01-01 to 2025-12-31
Inventory: 2024-01-01 to 2025-12-01

INVALID DATES
----------------------------------------
Sales: 0
Calendar: 0
Inventory: 0

In [9]:
sales_skus = set(sales_daily["SKU"].unique())
inventory_skus = set(inventory["SKU"].unique())
master_skus = set(sku_master["sku_id"].unique())

print("Sales unique SKUs:", len(sales_skus))
print("Inventory unique SKUs:", len(inventory_skus))
print("Master unique SKUs:", len(master_skus))

print("\nExample Sales SKUs:")
print(sorted(sales_skus)[:10])

print("\nExample Inventory SKUs:")
print(sorted(inventory_skus)[:10])

print("\nExample Master SKUs:")
print(sorted(master_skus)[:10])

print("\nSales SKUs matching master directly:",
      len(sales_skus & master_skus))

print("Inventory SKUs matching master directly:",
      len(inventory_skus & master_skus))

Sales unique SKUs: 50
Inventory unique SKUs: 200
Master unique SKUs: 5000

Example Sales SKUs:
['SKU001', 'SKU002', 'SKU003', 'SKU004', 'SKU005', 'SKU006', 'SKU007', 'SKU008', 'SKU009', 'SKU010']

Example Inventory SKUs:
['SKU001', 'SKU002', 'SKU003', 'SKU004', 'SKU005', 'SKU006', 'SKU007', 'SKU008', 'SKU009', 'SKU010']

Example Master SKUs:
['SKU00001', 'SKU00002', 'SKU00003', 'SKU00004', 'SKU00005', 'SKU00006', 'SKU00007', 'SKU00008', 'SKU00009', 'SKU00010']

Sales SKUs matching master directly: 0
Inventory SKUs matching master directly: 0

In [10]:
sample_skus = sorted(sales_skus)[:10]

print("Possible SKU mapping:")
for sku in sample_skus:
    converted = "SKU" + sku.replace("SKU", "").zfill(5)
    print(f"{sku}  ->  {converted}  ->  {converted in master_skus}")

Possible SKU mapping:
SKU001  ->  SKU00001  ->  True
SKU002  ->  SKU00002  ->  True
SKU003  ->  SKU00003  ->  True
SKU004  ->  SKU00004  ->  True
SKU005  ->  SKU00005  ->  True
SKU006  ->  SKU00006  ->  True
SKU007  ->  SKU00007  ->  True
SKU008  ->  SKU00008  ->  True
SKU009  ->  SKU00009  ->  True
SKU010  ->  SKU00010  ->  True

In [11]:
print("SALES DAILY")
print("-" * 50)

print("Negative Units Sold:",
      (sales_daily["Units_Sold"] < 0).sum())

print("Zero Units Sold:",
      (sales_daily["Units_Sold"] == 0).sum())

print("Negative Revenue:",
      (sales_daily["Revenue"] < 0).sum())

print("Negative Price:",
      (sales_daily["Price"] < 0).sum())

print("\nINVENTORY")
print("-" * 50)

print("Negative Current Stock:",
      (inventory["Current_Stock"] < 0).sum())

print("Negative On Order:",
      (inventory["On_Order"] < 0).sum())

print("Negative Lead Time:",
      (inventory["Lead_Time_Days"] < 0).sum())

print("Negative Safety Stock:",
      (inventory["Safety_Stock"] < 0).sum())

print("Negative Reorder Point:",
      (inventory["Reorder_Point"] < 0).sum())

print("Negative Inventory Value:",
      (inventory["Inventory_Value"] < 0).sum())

print("\nSKU MASTER")
print("-" * 50)

print("Negative Unit Price:",
      (sku_master["unit_price"] < 0).sum())

print("Negative Cost Price:",
      (sku_master["cost_price"] < 0).sum())

SALES DAILY
--------------------------------------------------
Negative Units Sold: 0
Zero Units Sold: 202
Negative Revenue: 0
Negative Price: 0

INVENTORY
--------------------------------------------------
Negative Current Stock: 0
Negative On Order: 0
Negative Lead Time: 0
Negative Safety Stock: 0
Negative Reorder Point: 0
Negative Inventory Value: 0

SKU MASTER
--------------------------------------------------
Negative Unit Price: 0
Negative Cost Price: 0

In [12]:
calculated_revenue = (
    sales_daily["Units_Sold"] *
    sales_daily["Price"]
)

revenue_difference = (
    sales_daily["Revenue"] - calculated_revenue
).abs()

print("Maximum revenue difference:",
      revenue_difference.max())

print("Rows with difference > 0.01:",
      (revenue_difference > 0.01).sum())

Maximum revenue difference: 5.820766091346741e-11
Rows with difference > 0.01: 0

In [13]:
# Standardize SKU identifiers without modifying the raw values

sales_daily["SKU_Standard"] = (
    sales_daily["SKU"]
    .str.replace("SKU", "", regex=False)
    .astype(int)
    .astype(str)
    .str.zfill(5)
    .radd("SKU")
)

inventory["SKU_Standard"] = (
    inventory["SKU"]
    .str.replace("SKU", "", regex=False)
    .astype(int)
    .astype(str)
    .str.zfill(5)
    .radd("SKU")
)

sku_master["SKU_Standard"] = sku_master["sku_id"]

print("Sales SKU examples:")
display(sales_daily[["SKU", "SKU_Standard"]].drop_duplicates().head(10))

print("\nInventory SKU examples:")
display(inventory[["SKU", "SKU_Standard"]].drop_duplicates().head(10))

print("\nMaster SKU examples:")
display(sku_master[["sku_id", "SKU_Standard"]].drop_duplicates().head(10))

Sales SKU examples:

      SKU SKU_Standard
0  SKU001     SKU00001
1  SKU002     SKU00002
2  SKU003     SKU00003
3  SKU004     SKU00004
4  SKU005     SKU00005
5  SKU006     SKU00006
6  SKU007     SKU00007
7  SKU008     SKU00008
8  SKU009     SKU00009
9  SKU010     SKU00010

Inventory SKU examples:

      SKU SKU_Standard
0  SKU001     SKU00001
1  SKU002     SKU00002
2  SKU003     SKU00003
3  SKU004     SKU00004
4  SKU005     SKU00005
5  SKU006     SKU00006
6  SKU007     SKU00007
7  SKU008     SKU00008
8  SKU009     SKU00009
9  SKU010     SKU00010

Master SKU examples:

     sku_id SKU_Standard
0  SKU00001     SKU00001
1  SKU00002     SKU00002
2  SKU00003     SKU00003
3  SKU00004     SKU00004
4  SKU00005     SKU00005
5  SKU00006     SKU00006
6  SKU00007     SKU00007
7  SKU00008     SKU00008
8  SKU00009     SKU00009
9  SKU00010     SKU00010

In [14]:
# Validate standardized SKU mappings

sales_mapping_check = sales_daily["SKU_Standard"].isin(
    sku_master["SKU_Standard"]
)

inventory_mapping_check = inventory["SKU_Standard"].isin(
    sku_master["SKU_Standard"]
)

print("Sales SKUs not found in SKU master:",
      (~sales_mapping_check).sum())

print("Inventory SKUs not found in SKU master:",
      (~inventory_mapping_check).sum())

print("\nSales unique standardized SKUs:",
      sales_daily["SKU_Standard"].nunique())

print("Inventory unique standardized SKUs:",
      inventory["SKU_Standard"].nunique())

print("SKU master unique standardized SKUs:",
      sku_master["SKU_Standard"].nunique())

Sales SKUs not found in SKU master: 0
Inventory SKUs not found in SKU master: 0

Sales unique standardized SKUs: 50
Inventory unique standardized SKUs: 200
SKU master unique standardized SKUs: 5000

In [15]:
quality_summary = pd.DataFrame({
    "Dataset": [
        "Sales Daily",
        "Calendar",
        "Inventory Snapshots",
        "SKU Master"
    ],
    "Rows": [
        len(sales_daily),
        len(calendar),
        len(inventory),
        len(sku_master)
    ],
    "Columns": [
        sales_daily.shape[1],
        calendar.shape[1],
        inventory.shape[1],
        sku_master.shape[1]
    ],
    "Duplicate Rows": [
        sales_daily.duplicated().sum(),
        calendar.duplicated().sum(),
        inventory.duplicated().sum(),
        sku_master.duplicated().sum()
    ]
})

display(quality_summary)

               Dataset   Rows  Columns  Duplicate Rows
0          Sales Daily  36550        7               0
1             Calendar    731       11               0
2  Inventory Snapshots   4800        9               0
3           SKU Master   5000        8               0

In [16]:
# Create processed-data directory
PROCESSED_PATH = PROJECT_PATH / "data" / "processed"
PROCESSED_PATH.mkdir(parents=True, exist_ok=True)

# Save processed datasets
sales_daily.to_csv(
    PROCESSED_PATH / "sales_daily_clean.csv",
    index=False
)

calendar.to_csv(
    PROCESSED_PATH / "calendar_clean.csv",
    index=False
)

inventory.to_csv(
    PROCESSED_PATH / "inventory_snapshots_clean.csv",
    index=False
)

sku_master.to_csv(
    PROCESSED_PATH / "sku_master_clean.csv",
    index=False
)

print("Processed datasets saved successfully.")
print("\nLocation:", PROCESSED_PATH)

for file in sorted(PROCESSED_PATH.glob("*.csv")):
    print(f"{file.name} — {file.stat().st_size / 1024:.2f} KB")

Processed datasets saved successfully.

Location: c:\Users\User\Desktop\foresight\data\processed
calendar_clean.csv — 34.67 KB
inventory_snapshots_clean.csv — 256.45 KB
sales_daily_clean.csv — 1770.61 KB
sku_master_clean.csv — 497.03 KB